# Generated by Django 5.1 on 2024-08-14 20:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_guest_leader_groupmember_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
